apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "open-match-tutorial.mmfName" . }}
  namespace: {{ .Release.Namespace }}
  # annotations: 
  #   checksum/config:
  labels:
    {{- include "open-match-tutorial.labels" . | nindent 4 }}
    component: mmf
spec:
  replicas: {{ .Values.mmf.replicas }}
  selector:
    matchLabels:
      {{- include "open-match-tutorial.selectorLabels" . | nindent 6 }}
      component: mmf
  template:
    metadata:
      namespace: {{ .Release.Namespace }}
      annotations:
      labels:
        {{- include "open-match-tutorial.selectorLabels" . | nindent 8 }}
        component: mmf
    spec:
      containers:
      - name: mmf
        image: "{{ .Values.mmf.images }}:{{ .Values.mmf.tag }}"
        ports:
        - containerPort: {{ .Values.mmf.port }}
        imagePullPolicy: {{ .Values.mmf.pullPolicy }}
        volumeMounts:
        - name: config-volume
          mountPath: /etc/open-match-tutorial
      volumes:
      - name: config-volume
        configMap:
          name: {{ include "open-match-tutorial.fullname" . }}
---
kind: Service
apiVersion: v1
metadata:
  name: {{ include "open-match-tutorial.mmfName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "open-match-tutorial.labels" . | nindent 4 }}
    component: mmf
spec:
  selector:
    {{- include "open-match-tutorial.selectorLabels" . | nindent 4 }}
    component: mmf
  type: {{ .Values.mmf.serviceType }}
{{- if eq .Values.mmf.serviceType "ClusterIP" }}
  clusterIP: None
{{- end }}
  ports:
  - name: grpc
    protocol: TCP
    port: {{ .Values.mmf.port }}
