// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.25.1
// source: proto/gamefront.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EntryGameRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *EntryGameRequest) Reset() {
	*x = EntryGameRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_gamefront_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EntryGameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntryGameRequest) ProtoMessage() {}

func (x *EntryGameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gamefront_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntryGameRequest.ProtoReflect.Descriptor instead.
func (*EntryGameRequest) Descriptor() ([]byte, []int) {
	return file_proto_gamefront_proto_rawDescGZIP(), []int{0}
}

func (x *EntryGameRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type EntryGameResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TicketId string `protobuf:"bytes,1,opt,name=ticket_id,json=ticketId,proto3" json:"ticket_id,omitempty"`
}

func (x *EntryGameResponse) Reset() {
	*x = EntryGameResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_gamefront_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EntryGameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntryGameResponse) ProtoMessage() {}

func (x *EntryGameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_gamefront_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntryGameResponse.ProtoReflect.Descriptor instead.
func (*EntryGameResponse) Descriptor() ([]byte, []int) {
	return file_proto_gamefront_proto_rawDescGZIP(), []int{1}
}

func (x *EntryGameResponse) GetTicketId() string {
	if x != nil {
		return x.TicketId
	}
	return ""
}

var File_proto_gamefront_proto protoreflect.FileDescriptor

var file_proto_gamefront_proto_rawDesc = []byte{
	0x0a, 0x15, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x61, 0x6d, 0x65, 0x66, 0x72, 0x6f, 0x6e,
	0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x67, 0x61, 0x6d, 0x65, 0x66, 0x72, 0x6f,
	0x6e, 0x74, 0x22, 0x26, 0x0a, 0x10, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x47, 0x61, 0x6d, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x30, 0x0a, 0x11, 0x45, 0x6e,
	0x74, 0x72, 0x79, 0x47, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x1b, 0x0a, 0x09, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x74, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x49, 0x64, 0x32, 0x5e, 0x0a, 0x10,
	0x47, 0x61, 0x6d, 0x65, 0x46, 0x72, 0x6f, 0x6e, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x4a, 0x0a, 0x09, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x47, 0x61, 0x6d, 0x65, 0x12, 0x1b, 0x2e,
	0x67, 0x61, 0x6d, 0x65, 0x66, 0x72, 0x6f, 0x6e, 0x74, 0x2e, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x47,
	0x61, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x67, 0x61, 0x6d,
	0x65, 0x66, 0x72, 0x6f, 0x6e, 0x74, 0x2e, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x47, 0x61, 0x6d, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x30, 0x01, 0x42, 0x09, 0x5a, 0x07,
	0x2e, 0x2e, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_gamefront_proto_rawDescOnce sync.Once
	file_proto_gamefront_proto_rawDescData = file_proto_gamefront_proto_rawDesc
)

func file_proto_gamefront_proto_rawDescGZIP() []byte {
	file_proto_gamefront_proto_rawDescOnce.Do(func() {
		file_proto_gamefront_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_gamefront_proto_rawDescData)
	})
	return file_proto_gamefront_proto_rawDescData
}

var file_proto_gamefront_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_gamefront_proto_goTypes = []interface{}{
	(*EntryGameRequest)(nil),  // 0: gamefront.EntryGameRequest
	(*EntryGameResponse)(nil), // 1: gamefront.EntryGameResponse
}
var file_proto_gamefront_proto_depIdxs = []int32{
	0, // 0: gamefront.GameFrontService.EntryGame:input_type -> gamefront.EntryGameRequest
	1, // 1: gamefront.GameFrontService.EntryGame:output_type -> gamefront.EntryGameResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_gamefront_proto_init() }
func file_proto_gamefront_proto_init() {
	if File_proto_gamefront_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_gamefront_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EntryGameRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_gamefront_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EntryGameResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_gamefront_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_gamefront_proto_goTypes,
		DependencyIndexes: file_proto_gamefront_proto_depIdxs,
		MessageInfos:      file_proto_gamefront_proto_msgTypes,
	}.Build()
	File_proto_gamefront_proto = out.File
	file_proto_gamefront_proto_rawDesc = nil
	file_proto_gamefront_proto_goTypes = nil
	file_proto_gamefront_proto_depIdxs = nil
}
