director:
  images: utahkt/open-match-tutorial-director
  tag: latest
  pullPolicy: Always
gamefront:
  replicas: 1
  images: utahkt/open-match-tutorial-front
  tag: latest
  port: 54321
  pullPolicy: Always
  serviceType: NodePort
  nodePort: 30021
gameserver:
  replicas: 1
  images: utahkt/open-match-tutorial-gameserver
  tag: latest
  port: 7654
  pullPolicy: Always
  serviceType: NodePort
  nodePort: 30054
  memberNum: 3
  timeout: 30
mmf:
  replicas: 1
  images: utahkt/open-match-tutorial-mmf
  tag: latest
  port: 50502
  pullPolicy: Always
  serviceType: ClusterIP
  name: default
common:
  tag: default
  openMatch:
    frontendEndpoint: "open-match-frontend.open-match.svc.cluster.local:50504"
    backendEndpoint: "open-match-backend.open-match.svc.cluster.local:50505"
    queryEndpoint: "open-match-query.open-match.svc.cluster.local:50503"
